In [2]:
import pandas as pd
import numpy as np

In [117]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

In [74]:
A[-1::-1]
np.eye(5, k=1) # k> step with duong cheo chinh


array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.diag([3,5,5]) # tra ve matrix duong cheo neu tham so la 1 array
np.diag(A)       # tra ve duong cheo neu tham so la 1 matrix

array([[3, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [95]:
np.sum(A, axis=0)

array([15, 18, 21, 24])

In [82]:
A[[0,1]][0:1]

array([[1, 2, 3]])

In [101]:
def af(n:int):
    return np.diag(np.array(np.arange(1,n), dtype=int), k = -1)

def myfunc(A:np.array):
    a = A[::2, ::2]
    return np.sum(a)

def myfuncA(A:np.array):
    a = np.min(A, axis=1) 
    b = np.max(A, axis=1)
    return np.sum(b-a)

In [ ]:
af(3)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [ ]:
myfuncA(A)

np.float64(9.0)

In [110]:
A.reshape((3,1,-1), order="C")

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [ ]:
x = np.arange(1,13)
a.reshape(3,4).transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
x = np.random.randn(100)
y = np.random.randn(100)

np.cov(x,y) # hiệp phương sai

array([[ 1.21602629, -0.04440166],
       [-0.04440166,  0.85135555]])

In [ ]:
np.var(x, ddof=1) # ddof: bậc tự do, var: phương sai

np.float64(1.216026289958991)

In [125]:
np.std(x, ddof=1)

np.float64(1.1027358205658284)