- np.random.rand(n): sinh ra n số trong nửa đoạn [0, 1) theo uniform distribution (phân phối đều)
- np.random.seed(n): đảm bảo nếu gieo cùng 1 seed thì kết quả trả về của rand là ko đổi 
- np.random.randn(n): sinh ra n số theo phân phối chuẩn Gaussian với kỳ vọng và phương sai là 0, 1
- np.random.normal(loc, scale, size): 
    - loc: shift distribution left or right on X axis (loc=μ)
    - scale: spread of dist (scale=σ)
- np.random.randint(from, to, size=number or tuple)

In [1]:
import numpy as np

In [4]:
np.random.randn(4).reshape(2,2)

array([[ 0.6302703 , -2.07414318],
       [-1.10163209,  1.25636176]])

In [17]:
def generate_normal_dist(mu: float, sigma: float, m: int, n: int):
    arr = np.random.randn(m*n)
    np.random.seed(42)
    arr = arr * sigma + mu
    return arr.reshape(m,n)

In [18]:
generate_normal_dist(1,1,4,2)

array([[1.49671415, 0.8617357 ],
       [1.64768854, 2.52302986],
       [0.76584663, 0.76586304],
       [2.57921282, 1.76743473]])

In [4]:
np.random.normal(loc=50, scale=5, size=8) #(loc=μ, scale=σ, size=n)

array([46.47822953, 58.167209  , 48.13956875, 52.52616101, 48.37012017,
       53.76045668, 49.06804908, 53.90554376])

In [5]:
np.random.randint(2,5,((3,2)))

array([[2, 3],
       [4, 4],
       [2, 2]], dtype=int32)

In [6]:
np.random.permutation(10) # 1 hoán vị của các số từ 0-9

array([9, 3, 0, 8, 6, 7, 4, 5, 2, 1], dtype=int32)