In [1]:
import pandas as pd
import numpy as np 

### concat & concatenate
1. np.concatenate(axis = [0,1])
2. pd.concat(axis)

- np.stack(axis)
- np.vstack(): vertical stack 
- np.hstack(): horizontal stack 
- np.dstack(): dimension stack 

In [4]:
a = np.linspace(2,10,5, dtype=int)
b = np.linspace(20,50,5, dtype=int)

a, b

(array([ 2,  4,  6,  8, 10]), array([20, 27, 35, 42, 50]))

In [ ]:
np.concat([a,b]) # same as np.concat([a,b], axis=None)

array([ 2,  4,  6,  8, 10, 20, 27, 35, 42, 50])

In [14]:
a = np.array([np.linspace(2,10,5, dtype=int)])
b = np.array([np.linspace(20,50,5, dtype=int)])

In [20]:
print(a)
print(b)

[[ 2  4  6  8 10]]
[[20 27 35 42 50]]


In [ ]:
np.concatenate((a,b), axis=None) 

array([1, 2, 3, 4, 5, 6])

In [37]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [38]:
np.concatenate((a,b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [41]:
df = pd.read_csv('suurimmatkaupungit.csv')
df.head(2)

Alue  Väkiluku, 2024  Alueella olevia työpaikkoja, 2023  id
0  Helsinki          684018                             430886  34
1     Espoo          320931                             138103  12

In [ ]:
df1 = df['Alue']
df2 = df['Alueella olevia työpaikkoja, 2023']

df3 = pd.concat((df1, df2), axis=1)
df3.head(2)